---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../openshift
  - control-plane.yaml
namespace: odh-notebook-controller-system
configMapGenerator:
  - name: config
    behavior: replace
    literals:
      - USE_ISTIO=true
      - ISTIO_GATEWAY=opendatahub/odh-gateway

# TODO add more things

patchesJson6902:
  - target:
      group: maistra.io
      version: v2
      kind: ServiceMeshControlPlane
      namespace: odh-notebook-controller-system
      name: basic
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: istio-system